import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const baseUrl = process.env.NEXT_PUBLIC_BASE_PATH || '';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: `${baseUrl}/favicon.svg`,
  },
};

import { Navbar } from "@/components/navbar";
import { SiteFooter } from "@/components/site-footer";

// ... existing code ...

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`font-sans antialiased bg-black text-white min-h-screen overflow-x-hidden`}
      >
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-1 w-full bg-black">{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
